### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by ibrahimsag** [JDBurnZ/pyminfraud#11]
can we update the pypi package with the latest changes?

**Comment by JDBurnZ** [comment]
Yes, please!

**Comment by ibrahimsag** [comment]
please :)

**Comment by JDBurnZ** [comment]
sorry, that wasn't to come off as a correction-- i thought you were aking if it was cool if you updated the pypi package yourself. i didn't actually post that package, another contributor did... i'll need to look into how to update that.

**Comment by ibrahimsag** [comment]
Gratitudes to whoever can do that :evergreen_tree:
