### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by cpburnz** [JDBurnZ/pyminfraud#8]
According to [LICENSE.md](https://github.com/JDBurnZ/pyminfraud/blob/master/LICENSE.md), the license is MIT. But according to [pyminfraud/\__init__.py](https://github.com/JDBurnZ/pyminfraud/blob/master/pyminfraud/__init__.py#L6-8), the license is CC BY 3.0.

**Comment by JDBurnZ** [comment]
Thanks for pointing this out. Fixing now.
